### PR TITLE
master

### PR DESCRIPTION
**Pull request by jimkont**
rfdunit testing

### CODE REVIEW

**Comment by sandroacoelho** [comment]
Hi @jimkont. Thanks for the PR :+1:

**Comment by sandroacoelho** [comment]
Hi @jimkont 

Thanks for the PR :+1: 

I will check why the tests have failed

**Comment by jimkont** [comment]
Soon I will make a new version for RDFUnit and you can remove the snapshot release.
for the  ontology we can include 

```
            <dependency>
                <groupId>org.nlp2rdf.ontologies</groupId>
                <artifactId>persistence.uni-leipzig.org</artifactId>
                <version>2.0.0-SNAPSHOT</version>
            </dependency>
```

to use the resource instead of the http lookup but we will have to publish the org.nlp2rdf repos to maven central to keep the repo clean from local dependencies

**Comment by jimkont** [comment]
Also note that with the newest jena version, java 8 is required

**Pull request merged**
